version: "3"
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - miriad-dump-network

networks:
  miriad-dump-network:
    driver: bridge