version: "3"
services:
  miriad-dump-prod:
    container_name: miriad-dump-production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - nms
    links:
      - db
      - nms
    networks:
      - miriad-dump-network
  db:
    image: postgres:12.2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - miriad-dump-network

networks:
  miriad-dump-network:
    driver: bridge